// ============================================================
//  lib/fallback-data.ts — Static fallback data
//  Used ONLY when the API is unreachable (build time, CI).
//  Real data comes from the backend API; this keeps the site
//  compilable and the UI non-empty during development.
// ============================================================

import type { Project, BlogPost, Skill, Experience, Achievement, SiteSettings } from './types';

export const FALLBACK_SETTINGS: SiteSettings = {
  id: 'singleton',
  name: 'Rohit Malviya',
  tagline: 'Full-Stack Engineer',
  email: 'rohitbmalviya@gmail.com',
  location: 'Pune, India',
  socials: {
    github: 'https://github.com/rohithumancloud',
    linkedin: 'https://linkedin.com/in/rohitbmalviya',
  },
  resumeUrl: '/resume.pdf',
  defaultTheme: 'DARK',
  footerText: 'Designed & built by Rohit Malviya — Next.js + Tailwind',
  ogTitle: 'Rohit Malviya — Full-Stack Engineer',
  ogDescription:
    'Full-stack engineer (2+ yrs) building production SaaS & bank-grade systems across TypeScript, Go, Python & Java.',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const FALLBACK_PROJECTS: Project[] = [
  {
    id: '1',
    slug: 'scb-monte-carlo',
    title: 'SCB Monte Carlo Platform',
    oneLiner: 'Bank-grade Monte Carlo portfolio-simulation platform for Siam Commercial Bank.',
    role: 'Sole architect & engineer — entire platform',
    tags: ['Python', 'TensorFlow', 'FastAPI', 'ARQ', 'Oracle', 'Kubernetes', 'Helm'],
    stack: ['Python', 'TensorFlow', 'FastAPI', 'ARQ', 'Oracle', 'Kubernetes', 'Helm'],
    metric: '3 services · ~1,242 tests · Cholesky-GBM engine',
    proofType: 'ARCHITECTURE',
    liveUrl: null,
    screenshots: [],
    architectureImg: null,
    overview:
      'A production Monte Carlo platform that ingests the bank\'s fund/price/FX data over SFTP, syncs it to Oracle, and runs TensorFlow GBM simulations with Cholesky-correlated multi-asset paths.',
    contribution:
      'Designed and built all three services + infra, independently — the FastAPI + ARQ/Redis async engine, the Cholesky-correlated GBM math (TensorFlow), Oracle persistence, the SFTP→Oracle data pipeline, the Helm/OpenShift deployment, and a ~1,242-test suite.',
    body: '',
    featured: true,
    order: 0,
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    slug: 'teamcast',
    title: 'Teamcast',
    oneLiner: 'AI-powered hiring & assessment SaaS (candidates, clients, partners, support).',
    role: 'Owned the ~185-endpoint Client backend + Candidate/Client portals',
    tags: ['Express', 'Prisma', 'PostgreSQL', 'Next.js', 'LiveKit', 'Convex', 'Vertex AI'],
    stack: ['Express', 'Prisma', 'PostgreSQL', 'Next.js', 'LiveKit', 'Convex', 'GCP'],
    metric: '148 Prisma models · ~185-endpoint backend',
    proofType: 'LIVE_DEMO',
    liveUrl: null,
    screenshots: [],
    architectureImg: null,
    overview:
      'Full hiring-lifecycle platform — job posting → AI candidate matching → 3-stage AI assessment funnel → AI-proctored LiveKit interviews → hire.',
    contribution:
      'Built & owned the Client backend (~185 endpoints) and the Candidate/Client Next.js portals.',
    body: '',
    featured: true,
    order: 1,
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    slug: 'meet-scribe',
    title: 'Meet Scribe',
    oneLiner: 'AI meeting-notetaker that joins calls, records, transcribes & syncs to CRM.',
    role: 'Owned the bot-service + 41-route Stripe billing + 10-page admin/checkout',
    tags: ['Playwright', 'BullMQ', 'Gemini', 'GCS', 'Stripe', 'Express', 'Prisma'],
    stack: ['Playwright', 'BullMQ', 'Gemini', 'GCS', 'Stripe', 'Express', 'Prisma'],
    metric: '3 Playwright adapters · 41 billing routes',
    proofType: 'LIVE_DEMO',
    liveUrl: null,
    screenshots: [],
    architectureImg: null,
    overview:
      'A headless bot silently joins Teams/Zoom/Meet, captures audio to GCS, and produces diarized transcripts → summaries, MOM emails & CRM sync.',
    contribution:
      'Built the bot-service (3 Playwright platform adapters) and the 41-route Stripe billing domain + 10-page admin & checkout UI.',
    body: '',
    featured: true,
    order: 2,
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    slug: 'lease-oasis',
    title: 'Lease Oasis',
    oneLiner: 'UAE property-rental & lease-management platform (7-service microservices).',
    role: 'Owned Property/Admin/Inquiry/S3/Notification services + Python RAG + admin/operator UIs',
    tags: ['Express', 'TypeORM', 'PostgreSQL', 'FastAPI', 'LangGraph', 'Elasticsearch'],
    stack: ['Express', 'TypeORM', 'PostgreSQL', 'FastAPI', 'LangGraph', 'Elasticsearch', 'Next.js'],
    metric: '7 services · 63 shared entities · 14-page admin + 8-page operator',
    proofType: 'LIVE_DEMO',
    liveUrl: null,
    screenshots: [],
    architectureImg: null,
    overview:
      'Multi-sided property platform (landlords, agencies, agents, operators) with credit/subscription billing, Elasticsearch search, and a conversational AI assistant.',
    contribution:
      'Built the Property/Admin/Inquiry/S3/Notification backend services and a Python RAG microservice (FastAPI + LangGraph over 768-dim Gemini embeddings).',
    body: '',
    featured: true,
    order: 3,
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    slug: 'medic-ai',
    title: 'Medic AI',
    oneLiner: 'Travel-insurance SaaS aggregator (insurers → agency partners → issuer agents).',
    role: 'Owned the 34-route Partner ecosystem + built 4 role-specific portals',
    tags: ['Express', 'Prisma', 'PostgreSQL', 'Next.js', 'pdfmake', 'AWS S3'],
    stack: ['Express', 'Prisma', 'PostgreSQL', 'Next.js', 'pdfmake', 'AWS S3'],
    metric: '34-route partner ecosystem · 4 role portals · credit facility',
    proofType: 'LIVE_DEMO',
    liveUrl: null,
    screenshots: [],
    architectureImg: null,
    overview:
      'B2B2C insurance distribution: insurers define products, partners onboard on a credit facility, issuer agents instantly issue policies with PDF certificate + QR verification.',
    contribution:
      'Built the 34-route Partner ecosystem and the 4 role portals (admin / insurer / partner / partner-employee) with role-based middleware routing.',
    body: '',
    featured: false,
    order: 4,
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    slug: 'avaloq-gbs',
    title: 'Avaloq GBS',
    oneLiner: 'MiFID II-compliant goal-based investment-advisory platform.',
    role: 'Frontend developer (Angular 19) on a regulated-finance product',
    tags: ['Angular 19', 'Signals', 'RxJS', 'TypeScript', 'Spring Boot', 'Java 21'],
    stack: ['Angular 19', 'Signals', 'RxJS', 'TypeScript', 'Spring Boot', 'Java 21'],
    metric: '~69 lazy routes · ~1,845 signal usages · MiFID II suitability',
    proofType: 'NONE',
    liveUrl: null,
    screenshots: [],
    architectureImg: null,
    overview:
      'Wealth-advisory platform — clients set goals, complete MiFID II risk-profiling & suitability, get matched to model portfolios, review advisor proposals & execute orders.',
    contribution:
      'Built features on the Angular 19 app using signal-based state, lazy-loaded routes, reactive forms & RxJS.',
    body: '',
    featured: false,
    order: 5,
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    slug: 'oms',
    title: 'OMS',
    oneLiner: 'Golang + Angular HR / biometric-attendance platform (deployed to 3 client orgs).',
    role: 'Full-stack engineer (intern) — backend + frontend',
    tags: ['Go', 'Gin', 'GORM', 'Angular 18', 'PostgreSQL', 'Docker'],
    stack: ['Go', 'Gin', 'GORM', 'Angular 18', 'PostgreSQL', 'Docker'],
    metric: '24 Go REST APIs · 27 Angular components · goroutine batch',
    proofType: 'NONE',
    liveUrl: null,
    screenshots: [],
    architectureImg: null,
    overview:
      'Ingests raw biometric punch files and reconstructs attendance via a custom punch-pairing algorithm; muster-roll + daily/monthly reports with Excel export.',
    contribution:
      'Built the 24-endpoint Go backend (clean architecture), goroutine-based batch processing (5,000+ records/file), and 27 Angular 18 components.',
    body: '',
    featured: false,
    order: 6,
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    slug: 'propertybull',
    title: 'PropertyBull',
    oneLiner: '4-microservice real-estate marketplace (Next.js + Express, polyglot).',
    role: 'Built auth, the Property module & buyer/seller/agent portals (intern)',
    tags: ['Next.js', 'Express', 'TypeORM', 'PostgreSQL', 'AWS S3', 'Jenkins'],
    stack: ['Next.js', 'Express', 'TypeORM', 'PostgreSQL', 'AWS S3', 'Jenkins'],
    metric: '4 microservices · JWT + Google OAuth · S3 uploads',
    proofType: 'LIVE_DEMO',
    liveUrl: null,
    screenshots: [],
    architectureImg: null,
    overview:
      'Real-estate platform connecting buyers, sellers, agents & service providers; MLS data sync, AI property search, Stripe billing.',
    contribution:
      'Built authentication (JWT, bcrypt, Google OAuth), the Property module, and the buyer/seller/agent portals; integrated AWS S3 uploads.',
    body: '',
    featured: false,
    order: 7,
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const FALLBACK_SKILLS: Skill[] = [
  // Languages
  { id: 's1', group: 'LANGUAGES', name: 'TypeScript', level: 'EXPERT', order: 0 },
  { id: 's2', group: 'LANGUAGES', name: 'Go', level: 'PROFICIENT', order: 1 },
  { id: 's3', group: 'LANGUAGES', name: 'Python', level: 'PROFICIENT', order: 2 },
  { id: 's4', group: 'LANGUAGES', name: 'Java', level: 'FAMILIAR', order: 3 },
  { id: 's5', group: 'LANGUAGES', name: 'Dart', level: 'FAMILIAR', order: 4 },
  // Frontend
  { id: 's6', group: 'FRONTEND', name: 'Angular 18/19', level: 'EXPERT', order: 0 },
  { id: 's7', group: 'FRONTEND', name: 'Next.js', level: 'EXPERT', order: 1 },
  { id: 's8', group: 'FRONTEND', name: 'React', level: 'EXPERT', order: 2 },
  { id: 's9', group: 'FRONTEND', name: 'Tailwind CSS', level: 'EXPERT', order: 3 },
  { id: 's10', group: 'FRONTEND', name: 'RxJS', level: 'PROFICIENT', order: 4 },
  // Backend
  { id: 's11', group: 'BACKEND', name: 'Express', level: 'EXPERT', order: 0 },
  { id: 's12', group: 'BACKEND', name: 'FastAPI', level: 'PROFICIENT', order: 1 },
  { id: 's13', group: 'BACKEND', name: 'Spring Boot', level: 'FAMILIAR', order: 2 },
  { id: 's14', group: 'BACKEND', name: 'Gin', level: 'PROFICIENT', order: 3 },
  { id: 's15', group: 'BACKEND', name: 'NestJS', level: 'PROFICIENT', order: 4 },
  // Data
  { id: 's16', group: 'DATA', name: 'PostgreSQL', level: 'EXPERT', order: 0 },
  { id: 's17', group: 'DATA', name: 'Prisma', level: 'EXPERT', order: 1 },
  { id: 's18', group: 'DATA', name: 'Oracle', level: 'FAMILIAR', order: 2 },
  { id: 's19', group: 'DATA', name: 'Redis', level: 'PROFICIENT', order: 3 },
  { id: 's20', group: 'DATA', name: 'Elasticsearch', level: 'FAMILIAR', order: 4 },
  { id: 's21', group: 'DATA', name: 'TypeORM', level: 'PROFICIENT', order: 5 },
  // Cloud / DevOps
  { id: 's22', group: 'CLOUD_DEVOPS', name: 'Docker', level: 'PROFICIENT', order: 0 },
  { id: 's23', group: 'CLOUD_DEVOPS', name: 'Kubernetes', level: 'PROFICIENT', order: 1 },
  { id: 's24', group: 'CLOUD_DEVOPS', name: 'GCP', level: 'PROFICIENT', order: 2 },
  { id: 's25', group: 'CLOUD_DEVOPS', name: 'AWS', level: 'PROFICIENT', order: 3 },
  { id: 's26', group: 'CLOUD_DEVOPS', name: 'GitHub Actions', level: 'PROFICIENT', order: 4 },
  { id: 's27', group: 'CLOUD_DEVOPS', name: 'Helm', level: 'PROFICIENT', order: 5 },
  // AI
  { id: 's28', group: 'AI', name: 'TensorFlow', level: 'FAMILIAR', order: 0 },
  { id: 's29', group: 'AI', name: 'LangChain/LangGraph', level: 'PROFICIENT', order: 1 },
  { id: 's30', group: 'AI', name: 'Gemini', level: 'PROFICIENT', order: 2 },
  { id: 's31', group: 'AI', name: 'RAG', level: 'PROFICIENT', order: 3 },
  { id: 's32', group: 'AI', name: 'Stripe', level: 'PROFICIENT', order: 4 },
];

export const FALLBACK_EXPERIENCE: Experience[] = [
  {
    id: 'e1',
    role: 'Software Engineer',
    company: 'Humancloud Technologies',
    location: 'Pune, India',
    startDate: '2024-07-01',
    endDate: 'Present',
    bullets: [
      'Architected a 3-service production Monte Carlo platform for Siam Commercial Bank (TensorFlow GBM + Cholesky, FastAPI + ARQ over Oracle, SFTP ingestion).',
      'Owned the ~185-endpoint Client backend on Teamcast (Express + Prisma) + Candidate/Client portals.',
      'Built Meet Scribe\'s bot-service (3 Playwright adapters, Gemini diarization) + 41-route Stripe billing + 10-page admin/checkout.',
      'Shipped Lease Oasis Property/Admin/Inquiry/S3/Notification services + a Python RAG microservice + 14-page admin & 8-page operator UIs.',
      'Built Medic AI\'s 34-route Partner ecosystem + 4 role portals; frontend on Avaloq GBS (Angular 19, MiFID II).',
    ],
    order: 0,
  },
  {
    id: 'e2',
    role: 'Software Developer Intern',
    company: 'Humancloud Technologies',
    location: 'Pune, India',
    startDate: '2024-01-01',
    endDate: '2024-06-30',
    bullets: [
      'Built OMS — a Go + Angular 18 HR/attendance platform across 3 client orgs (24 Go REST APIs, goroutine batch processing, custom punch-pairing algorithm).',
      'Built auth (JWT/bcrypt/Google OAuth), the Property module & buyer/seller/agent portals on PropertyBull (4-microservice real-estate platform); AWS S3 + Docker/Jenkins CI.',
    ],
    order: 1,
  },
];

export const FALLBACK_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'a1',
    title: '"Going Beyond" Award',
    description: 'Awarded by Humancloud Technologies for delivering critical production features across multiple projects.',
    year: '2025',
    type: 'AWARD',
    order: 0,
  },
  {
    id: 'a2',
    title: 'Simulix Mentorship',
    description: 'Mentored interns building Simulix — Humancloud\'s internal Monte Carlo demo platform.',
    year: '2025',
    type: 'MENTORING',
    order: 1,
  },
  {
    id: 'a3',
    title: 'B.E. in Artificial Intelligence & Data Science',
    description: 'Zeal College of Engineering & Research, Pune — CGPA 8.9/10',
    year: '2024',
    type: 'EDUCATION',
    order: 2,
  },
];

export const FALLBACK_BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    slug: 'bank-grade-monte-carlo-cholesky-gbm-tensorflow',
    title: 'Building a bank-grade Monte Carlo engine: Cholesky-correlated GBM in TensorFlow',
    excerpt:
      'How I architected a production Monte Carlo simulation platform for Siam Commercial Bank — from Cholesky-correlated GBM paths to FastAPI + ARQ async architecture.',
    coverImage: null,
    tags: ['Python', 'TensorFlow', 'Fintech', 'Architecture'],
    body: '',
    readingTime: 8,
    published: true,
    publishedAt: '2025-03-15T00:00:00.000Z',
    createdAt: '2025-03-15T00:00:00.000Z',
    updatedAt: '2025-03-15T00:00:00.000Z',
  },
  {
    id: 'b2',
    slug: 'designing-148-model-multi-tenant-hiring-platform',
    title: 'Designing a 148-model multi-tenant hiring platform',
    excerpt:
      'Deep dive into Teamcast\'s architecture: multi-tenancy rooted at company, a 3-stage AI assessment funnel, Express as source-of-truth + Convex for real-time, and BullMQ workers.',
    coverImage: null,
    tags: ['Architecture', 'Node.js', 'SaaS', 'TypeScript'],
    body: '',
    readingTime: 7,
    published: true,
    publishedAt: '2025-04-02T00:00:00.000Z',
    createdAt: '2025-04-02T00:00:00.000Z',
    updatedAt: '2025-04-02T00:00:00.000Z',
  },
  {
    id: 'b3',
    slug: '3-playwright-bots-that-join-your-meetings',
    title: '3 Playwright bots that silently join your meetings (Teams / Zoom / Meet)',
    excerpt:
      'Per-platform automation quirks, audio capture to GCS, and how I wired GCP Speech-to-Text + Gemini speaker diarization for a production AI meeting-notetaker.',
    coverImage: null,
    tags: ['Playwright', 'AI', 'Node.js', 'Automation'],
    body: '',
    readingTime: 6,
    published: true,
    publishedAt: '2025-05-10T00:00:00.000Z',
    createdAt: '2025-05-10T00:00:00.000Z',
    updatedAt: '2025-05-10T00:00:00.000Z',
  },
];
